product dashboard page missing bgcolor
marajput123/wesource-frontend pull request #18
Opened 2021-10-28 21:15 UTC by TinyEggRoll

product page  missing background color.

2021-10-29 18:46 UTC, marajput123 requested changes

2021-10-29 18:46 UTC, marajput123 commented on src/App.js
>                  path="/:productDashboardID"
This route is the same is landing page. I suggest you make it: "/<route>/:productDashboardID"

2021-10-29 18:46 UTC, marajput123 commented on src/components/MainProductBox.js
> +    history.push('/');
This will lead to the landing page. Change it what your dashboard route will be.

2021-11-03 18:02 UTC, TinyEggRoll commented
what does re-request review do? i'm going to click it

2021-11-03 19:35 UTC, marajput123 approved these changes

2021-11-18 02:38 UTC, merged